[2022-09-12T09:02:46.370+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: basic_cloud_scheduler_dag.hourly_cloud_calc manual__2022-09-12T09:02:45.849257+00:00 [queued]>
[2022-09-12T09:02:46.377+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: basic_cloud_scheduler_dag.hourly_cloud_calc manual__2022-09-12T09:02:45.849257+00:00 [queued]>
[2022-09-12T09:02:46.378+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2022-09-12T09:02:46.378+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 1
[2022-09-12T09:02:46.378+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2022-09-12T09:02:46.389+0000] {taskinstance.py:1389} INFO - Executing <Task(SimpleHttpOperator): hourly_cloud_calc> on 2022-09-12 09:02:45.849257+00:00
[2022-09-12T09:02:46.392+0000] {standard_task_runner.py:52} INFO - Started process 17090 to run task
[2022-09-12T09:02:46.394+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'basic_cloud_scheduler_dag', 'hourly_cloud_calc', 'manual__2022-09-12T09:02:45.849257+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/basic_cloud_scheduler_dag.py', '--cfg-path', '/tmp/tmppiv2txrx', '--error-file', '/tmp/tmpb424fesm']
[2022-09-12T09:02:46.394+0000] {standard_task_runner.py:80} INFO - Job 6: Subtask hourly_cloud_calc
[2022-09-12T09:02:46.433+0000] {task_command.py:371} INFO - Running <TaskInstance: basic_cloud_scheduler_dag.hourly_cloud_calc manual__2022-09-12T09:02:45.849257+00:00 [running]> on host a73a9db5b359
[2022-09-12T09:02:46.487+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=basic_cloud_scheduler_dag
AIRFLOW_CTX_TASK_ID=hourly_cloud_calc
AIRFLOW_CTX_EXECUTION_DATE=2022-09-12T09:02:45.849257+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-09-12T09:02:45.849257+00:00
[2022-09-12T09:02:46.487+0000] {http.py:121} INFO - Calling HTTP method
[2022-09-12T09:02:46.494+0000] {base.py:68} INFO - Using connection ID 'cloud_calc' for task execution.
[2022-09-12T09:02:46.494+0000] {http.py:148} INFO - Sending 'GET' to url: http://r_server:8888/cloud/C18AC097
[2022-09-12T09:02:46.737+0000] {http.py:125} INFO - {"success":["The request has been queued. You will receive an email when the process is complete."]}
[2022-09-12T09:02:46.737+0000] {taskinstance.py:1902} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/http/operators/http.py", line 132, in execute
    return self.response_filter(response, **kwargs)
  File "/opt/airflow/dags/basic_cloud_scheduler_dag.py", line 29, in <lambda>
    response_filter=lambda response: json.loads(response.text),
NameError: name 'json' is not defined
[2022-09-12T09:02:46.743+0000] {taskinstance.py:1412} INFO - Marking task as FAILED. dag_id=basic_cloud_scheduler_dag, task_id=hourly_cloud_calc, execution_date=20220912T090245, start_date=20220912T090246, end_date=20220912T090246
[2022-09-12T09:02:46.753+0000] {standard_task_runner.py:97} ERROR - Failed to execute job 6 for task hourly_cloud_calc (name 'json' is not defined; 17090)
[2022-09-12T09:02:46.766+0000] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-09-12T09:02:46.791+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
